### ISSUE TITLE
`--mode all` is mentioned on the documentation but missing on the implementation

### ISSUE THREAD

**Issue by tbrittoborges** [alevar/ORFanage#1]
Hi @alevar ,

I was testing ORFanage as a potential replacement for in-house code, and I found a few issues. For example, the mode `all` implementation is missing here:

https://github.com/alevar/ORFanage/blob/bb0055bad09f24d0c43f2415dba181466ffc5dc4/main.cpp#L22-L27

But is mentioned in the docs:

https://github.com/alevar/ORFanage/blob/bb0055bad09f24d0c43f2415dba181466ffc5dc4/README.rst#L100

**Comment by alevar** [comment]
Hi @tbrittoborges ,

Thank you for taking a close look at the software! I've been a bit pre-occupied with the testing and experiments, and left a few things (documentation) unchecked for a bit.

The "ALL" mode has been dropped for the initial release and the change needs to be reflected in the documentation (will fix it now).  It seemed to me that returning all possible ORFs would be a bit cluttering and confusing.

That being said, do you think it would be useful to your work or to someone else? The stats file currently outputs results of all comparisons and could potentially be used to examine alternative translations. But parsing and converting the stats file is cumbersome. If there is need - I could certainly re-implement the feature.

Curious to hear your thoughts. And thank you again for taking a look and testing the method!

**Comment by tbrittoborges** [comment]
Hi Ales,

thanks for the prompt action. 
> That being said, do you think it would be useful to your work or to someone else? 

Yes I agree it would be overwhelming for a normal user, but it would be useful for me and some of my colleagues working with alternative ORFs. In general we would clean it up and split by class before using it for visualization. 

I have a few other questions and I will open a new issue for them.

**Comment by alevar** [comment]
Hi Thiago,

I have introduced a mode to output all unique ORFs deduced by the method. It is very experimental (a lot needed a re-design and not everything has been tested yet), but seems to be a useful feature. Here is how it works:
1. enabled by --mode ALL.
2. Once all comparisons for a given transcript have been computed, the results are grouped by CDS, keeping track of all reference transcripts which produced these results.
3. For every CDS, the closest matching reference transcript is selected as a representative to be reported.
4. every CDS is written to the GTF output. To avoid duplicate transcript IDs (which can confuse downstream tools), the method appends CDS start and CDS end coordinates to each transcript in both GTF and stats outputs. This is only done when the ALL mode is selected.

Another neat side-effect of this implementation is that for each ORF the method now knows how many reference transcript comparisons yielded this particular CDS. I think it could be used as a primitive gauge of consistency of ORF ith the locus: the more references produce this ORF when fitted onto query transcript - the higher the consistency of the ORF. This result is independent of which mode is selected, and is now being reported both in the GTF as well as the stats outputs.

I hope this feature helps you in your work. I will test it some more, but please do let me know if you get a chance to try it out and if you run into any issues.

Ales

**Comment by tbrittoborges** [comment]
Hi Ales, thank you so much for implementing this feature. I will test it on Monday and get back to you.

4 Mar 2023 09:11:52 Ales Varabyou ***@***.***>:

> Hi Thiago,
> 
> I have introduced a mode to output all unique ORFs deduced by the method. It is very experimental (a lot needed a re-design and not everything has been tested yet), but seems to be a useful feature. Here is how it works:
> 
1. > enabled by --mode ALL.
2. > Once all comparisons for a given transcript have been computed, the results are grouped by CDS, keeping track of all reference transcripts which produced these results.
3. > For every CDS, the closest matching reference transcript is selected as a representative to be reported.
4. > every CDS is written to the GTF output. To avoid duplicate transcript IDs (which can confuse downstream tools), the method appends CDS start and CDS end coordinates to each transcript in both GTF and stats outputs. This is only done when the ALL mode is selected.
