### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by francicco** [alevar/ORFanage#4]
Hi,

First of all, great tool!

I'm trying to test ORFanage on my data, the example you provide works.

What I'm trying to do is the following, not sure if this is the correct use.

I have a closely related species of mine, from it I took all the proteins and I aligned them onto my genome with `miniprot`. That produced a gff/gtf annotation.

```
Scf0000001	miniprot	transcript	12553945	12558355	1273	+	.	ID=MP025776;Rank=1;Identity=0.9796;Positive=0.9918;Target=Mmen_g09862_i2 1 245
Scf0000001	miniprot	CDS	12553945	12554112	295	+	0	Parent=MP025776;Rank=1;Identity=0.9643;Target=Mmen_g09862_i2 1 56
Scf0000001	miniprot	CDS	12557047	12557275	418	+	0	Parent=MP025776;Rank=1;Identity=1.0000;Target=Mmen_g09862_i2 57 132
Scf0000001	miniprot	CDS	12557623	12557794	294	+	2	Parent=MP025776;Rank=1;Identity=1.0000;Target=Mmen_g09862_i2 133 189
Scf0000001	miniprot	CDS	12558190	12558352	266	+	1	Parent=MP025776;Rank=1;Identity=0.9455;Target=Mmen_g09862_i2 190 245
Scf0000001	miniprot	stop_codon	12558353	12558355	0	+	0	Parent=MP025776;Rank=1
```

I then map my RNAseq illumina reads onto my genome and call `Stringtie` to reconstract the transcriptome.

```
Scf0000001	StringTie	transcript	12553385	12558511	1000	+	.	gene_id "Mmex.Trimmed.766"; transcript_id "Mmex.Trimmed.766.1"; cov "11.659020"; FPKM "0.937141"; TPM "2.276772";
Scf0000001	StringTie	exon	12553385	12554112	1000	+	.	gene_id "Mmex.Trimmed.766"; transcript_id "Mmex.Trimmed.766.1"; exon_number "1"; cov "10.025447";
Scf0000001	StringTie	exon	12557047	12557293	1000	+	.	gene_id "Mmex.Trimmed.766"; transcript_id "Mmex.Trimmed.766.1"; exon_number "2"; cov "13.070750";
Scf0000001	StringTie	exon	12557623	12557794	1000	+	.	gene_id "Mmex.Trimmed.766"; transcript_id "Mmex.Trimmed.766.1"; exon_number "3"; cov "14.859105";
Scf0000001	StringTie	exon	12558190	12558511	1000	+	.	gene_id "Mmex.Trimmed.766"; transcript_id "Mmex.Trimmed.766.1"; exon_number "4"; cov "12.560042";
```

Now, instead of use TransDecoder and all that pipeline I was thinking to use `ORFanage` to annotate the `Stringtie` annotation with the `miniprot` mapping, by simply executing:

`orfanage --query Mmex.Trimmed.766.1.gtf --output Mmex.Trimmed.766.1.out.gtf MP025776.gff`

But I'm getting:

```
loading reference genome
loading reference transcriptomes
Segmentation fault
```

Any idea why?

Best
Francesco

**Comment by alevar** [comment]
Hi Francesco,

Thank you for trying out our method! I have not tested it in combination with miniprot before - but this sounds like a very interesting use case for working with non-reference genomes!

Does the error replicate if you provide the genome fasta file via the --reference parameter?

Thank you,

Ales

**Comment by francicco** [comment]
Hi Ales,

Yes, I thought it could be useful for non-reference genomes indeed! And yes, I tried with the genome too (`--reference`) 
F

**Comment by alevar** [comment]
Sorry, I accidentally closed the issue. I was able to replicate your issue and found that gclib used for parsing transcripts does not automatically assign missing geneIDs. I adopted the behavior defined in gffread - assigning transcript ID as gene ID for cases where gene ID is not available and can not be inferred. Your example worked well with the new version.

The new version is now available in the sources and as a static binary in the latest release. If all works well - I will update the bioconda release as well.

Thank you again for giving our method a try and kindly providing your feedback! We hope you find the method useful for your work!

Thank you,

Ales

**Comment by francicco** [comment]
Thanks a lot!!!! I'll test it!
F

**Comment by alevar** [comment]
Hi Francesco,

Were you able to test the patched version of the method?

Thank you,

**Comment by francicco** [comment]
Hi @alevar,

Yes, I tried but it didn't really work. This is how I execute it:

`orfanage --reference Genome --output Testoutput.gtf --query cufflinks.out.gtf miniprot.annOnly.gff`

the output only contains a few annotations and none of them has any CDS.
Not sure why, maybe this wasn't the real purpose of the tool...

Thanks a lot
F

**Comment by alevar** [comment]
Hi @francicco,

Thank you for testing the updated version of for providing your feedback. Your use-case, while not explicitely described, should certainly work properly and I would like to make sure it does. I created my own mini-setup attempting to recreate your experiment. I extracted proteins from the mane annotation on chromosome 21 and mapped them back to the human genome with miniprot. I then proceeded to run ORFanage to annotate a stringtie assembly of a random GTEx sample using the miniprot output.

The experiment worked as intended, producing valid output, when miniprot was run with the "--gtf" flag. However, with the "--gff" mode, the output could not be properly parsed by the gclib. Similarly gffread could not parse the output either.

If you have a moment, could you repeat your experiment with miniprot using the "--gtf" flag? I really do hope the method works, and if it doesn't will investigate further.

Thank you,

AS

**Comment by francicco** [comment]
Did that but it's not really working.
I attached a toy example.

`orfanage --reference Genomes.fasta --output OrfAnage --query query.gtf template.gtf`

F

[template.gtf.gz](https://github.com/alevar/ORFanage/files/12333394/template.gtf.gz)
[query.gtf.gz](https://github.com/alevar/ORFanage/files/12333397/query.gtf.gz)

**Comment by alevar** [comment]
Thank you, could you provide the genome sequence for the toy example as well?

AS

**Comment by francicco** [comment]
My bad! So sorry!
F

[Scf0000001.fa.gz](https://github.com/alevar/ORFanage/files/12337387/Scf0000001.fa.gz)

**Comment by alevar** [comment]
Thank you for providing your example dataset. The issue I encountered on your data was related to unexpected inputs in the query.gtf file this time. The isoQuant output contained "gene" records, which the software fruitlessly attempted to parse as transcripts leading to undefined behaviors. I now included an assertion which skips any records that can not be converted internally into a transcript representation.

On a related note, over the years I have found it incredibly helpful to run `gffread -T -F --keep-exon-attrs --force-exons <gtf_filename>` on all my annotations to preemptively identify and fix any issues by standardizing all outputs. ORFanage internally shares much of the parsing code with gffread and performs some of the standardization, but gffread is much more comprehensive.

Hope this works!

**Comment by francicco** [comment]
Hi @alevar,

Thanks a lot! Yes I use gffread a lot too, but it looks like gff annotations produced by a lot of tools don't really follow the same standards, so it's a bit of a mess!

So, what should I do? Is there a new binary available?

Thanks really a lot!
F

**Comment by alevar** [comment]
@francicco, yes - the source code and the binaries have been updated. I am withholding on updating the conda release for now until the issue is fully resolved.

Thank you!

AS

**Comment by francicco** [comment]
Hi @alevar,

Thanks a lot for all this. I tested the new code on the whole data I have and I noticed a weird behaviour of `ORFange`.

When I give all the data in the query and template some transcripts are not annotated with the corresponding CDS. I tested this by giving ORFanage only the transcript that is not annotated with the corresponding coordinates that it should receive.

Query:
```
Scf0000001	BRAKER_IsoQuant	transcript	409226	415861	100.0	+	.	gene_id "Scf0000001G54"; transcript_id "Scf0000001G54.1"; score "100.0";
Scf0000001	BRAKER_IsoQuant	exon	409226	409240	100.0	+	.	gene_id "Scf0000001G54"; transcript_id "Scf0000001G54.1"; exon_number "1"; score "100.0";
Scf0000001	BRAKER_IsoQuant	exon	409319	411098	100.0	+	.	gene_id "Scf0000001G54"; transcript_id "Scf0000001G54.1"; exon_number "2"; score "100.0";
Scf0000001	BRAKER_IsoQuant	exon	411550	413863	100.0	+	.	gene_id "Scf0000001G54"; transcript_id "Scf0000001G54.1"; exon_number "3"; score "100.0";
Scf0000001	BRAKER_IsoQuant	exon	414240	415861	100.0	+	.	gene_id "Scf0000001G54"; transcript_id "Scf0000001G54.1"; exon_number "4"; score "100.0";
```

Template:
```
Scf0000001	miniprot	gene	413488	414667	1248	+	.	gene_id "MPG013481";
Scf0000001	miniprot	transcript	413488	414667	1248	+	.	transcript_id "MPT013481"; gene_id "MPG013481";
Scf0000001	miniprot	exon	413488	413863	485	+	.	transcript_id "MPT013481"; gene_id "MPG013481";
Scf0000001	miniprot	CDS	413488	413863	485	+	0	transcript_id "MPT013481"; gene_id "MPG013481";
Scf0000001	miniprot	exon	414240	414667	763	+	.	transcript_id "MPT013481"; gene_id "MPG013481";
Scf0000001	miniprot	CDS	414240	414667	763	+	2	transcript_id "MPT013481"; gene_id "MPG013481";
```

`orfanage --rescue --mode LONGEST_MATCH --reference GENOME --output test --query query.gtf template.gtf`

The annotation now get annotated, but the coordinates do not correspond to the template, at least not entirely
```
Scf0000001	BRAKER_IsoQuant	transcript	409226	415861	.	+	.	transcript_id "Scf0000001G54.1"; gene_id "Scf0000001G54"; orfanage_duplicity "0"; orfanage_status "1"; orfanage_template "MPT013481"; orfanage_template_source "miniprot"; score "100.0";
Scf0000001	BRAKER_IsoQuant	exon	409226	409240	.	+	.	transcript_id "Scf0000001G54.1";
Scf0000001	BRAKER_IsoQuant	exon	409319	411098	.	+	.	transcript_id "Scf0000001G54.1";
Scf0000001	BRAKER_IsoQuant	exon	411550	413863	.	+	.	transcript_id "Scf0000001G54.1";
Scf0000001	ORFanage	CDS	413035	413863	.	+	0	transcript_id "Scf0000001G54.1";
Scf0000001	BRAKER_IsoQuant	exon	414240	415861	.	+	.	transcript_id "Scf0000001G54.1";
Scf0000001	ORFanage	CDS	414240	414667	.	+	2	transcript_id "Scf0000001G54.1";
```

1. Why the transcripts don't get annotated at the beginning
2. Why does it change the coordinates?

I'm sure there's something I'm now aware of
Thanks for your help
Best
F

**Comment by alevar** [comment]
Hi @francicco,

Glad to hear it's working for your use case now! I looked at your example locus in IGV and it seems to me what the method is doing is correct. Hopefully, a couple of screenshots below will illustrate why it was annotated the way it was.

Here is what the entire locus looks like, with the ORFanage output shown at the top, query GTF file in the middle panel and the template at the bottom panel. The tall blue segments designate CDS regions, and shorter ones are the untranslated exonic segments of the transfrags (as specified in the GTF files).
![image](https://github.com/alevar/ORFanage/assets/10055267/cbaf69b1-99fe-4570-ab02-f8e1fe735760)

If we zoom-in closer on where the translation ends, we can see that the template contains a stop codon and it is correctly matched when ORFanage annotates a CDS for the query.
![image](https://github.com/alevar/ORFanage/assets/10055267/293a62b6-668d-45be-ba45-274738ec0cac)

The start codon, however, is missing in the template. ORFanage, by default, will still try to use the incomplete reference sequence (even though the template CDS is considered invalid) and will search upstream for a suitable translation initiation site.
![image](https://github.com/alevar/ORFanage/assets/10055267/727dc3b3-ef73-45f2-ae9e-b9dcaa7d82cd)

Which is then found upstream on the query transfrag.
![image](https://github.com/alevar/ORFanage/assets/10055267/8989c21f-7518-417c-87b7-207931c8f896)

I hope this illustration helps explain how the method produced annotation for the locus you provided! I think you use case is very interesting and useful and hope the software works well for it.

Thank you,

AS
