### ISSUE TITLE
Not getting the best ORF

### ISSUE THREAD

**Issue by alexzaccaron** [alevar/ORFanage#6]
Hi,

First, thank you for developing ORFanage.

I got transcripts assembled with StringTie that I want to predict ORFs based on the reference genome. Thus, I started to test ORFanage, as it does exactly what I need. However, I noticed something strange in one particular gene of interest that has two isoforms. The canonical isoform has a small ORF of 282 bp, and the alternative isoform has an intron retention that causes a frameshift, but still produces a 291 bp ORF. However, ORFanage predicts a tiny ORF of 18 bp instead of the expected 291 bp ORF (see IGV snapshot below). I tried to change the `--mode` parameter to `LONGEST`, `LONGEST_MATCH`, and `START_MATCH`, but ORFanage always predicts the 18 bp ORF.

![igv_snapshot](https://github.com/alevar/ORFanage/assets/13971538/4a9d7301-56a9-4843-8707-4d3c8d30db79)

Why would ORFanage not predict the 291 bp ORF? Am I missing something or doing something wrong?

Here are the detail: 

ORFanage version: `ORFanage v1.2.0 (build date: UNKNOWN, git commit: UNKNOWN)`

call to ORFanage:
```
orfanage \
--query ecp22.gtf \
--output ecp22_orfs.gtf \
--reference CP090167.1.fasta \
reference.gtf
```

the query `ecp22.gtf`:
```
CP090167.1	StringTie	transcript	2949584	2950280	1000	+	.	gene_id "CLAFUR5_06022"; transcript_id "CLAFUR5_06022_R4.1.1dpi14_2";
CP090167.1	StringTie	exon	2949584	2950280	1000	+	.	gene_id "CLAFUR5_06022"; transcript_id "CLAFUR5_06022_R4.1.1dpi14_2";
CP090167.1	StringTie	transcript	2949794	2950131	1000	+	.	gene_id "CLAFUR5_06022"; transcript_id "CLAFUR5_06022_R5.1.2dpi6_2";
CP090167.1	StringTie	exon	2949794	2950007	1000	+	.	gene_id "CLAFUR5_06022"; transcript_id "CLAFUR5_06022_R5.1.2dpi6_2";
CP090167.1	StringTie	exon	2950064	2950131	1000	+	.	gene_id "CLAFUR5_06022"; transcript_id "CLAFUR5_06022_R5.1.2dpi6_2";
```

the reference fasta is from NCBI, accession [CP090167.1](https://www.ncbi.nlm.nih.gov/nuccore/CP090167.1/).

The template `reference.gtf `:
```
CP090167.1	Genbank	exon	2949794	2950007	.	+	.	gene_id "CLAFUR5_06022"; transcript_id "CLAFUR5_06022A"; ID "exon-CLAFUR5_06022A-1"; Parent "CLAFUR5_06022A"; gbkey "mRNA"; locus_tag "CLAFUR5_06022"; orig_protein_id "CLAFUR5_06022A"; orig_transcript_id "CLAFUR5_06022A"; product "Ecp2-2";
CP090167.1	Genbank	exon	2950064	2950131	.	+	.	gene_id "CLAFUR5_06022"; transcript_id "CLAFUR5_06022A"; ID "exon-CLAFUR5_06022A-2"; Parent "CLAFUR5_06022A"; gbkey "mRNA"; locus_tag "CLAFUR5_06022"; orig_protein_id "CLAFUR5_06022A"; orig_transcript_id "CLAFUR5_06022A"; product "Ecp2-2";
CP090167.1	Genbank	CDS	2949794	2950007	.	+	0	gene_id "CLAFUR5_06022"; transcript_id "CLAFUR5_06022A"; Dbxref "NCBI_GP:UJO18017.1"; ID "cds-UJO18017.1"; Name "UJO18017.1"; Parent "CLAFUR5_06022A"; gbkey "CDS"; locus_tag "CLAFUR5_06022"; orig_transcript_id "CLAFUR5_06022A"; product "Ecp2-2"; protein_id "UJO18017.1";
CP090167.1	Genbank	CDS	2950064	2950131	.	+	2	gene_id "CLAFUR5_06022"; transcript_id "CLAFUR5_06022A"; Dbxref "NCBI_GP:UJO18017.1"; ID "cds-UJO18017.1"; Name "UJO18017.1"; Parent "CLAFUR5_06022A"; gbkey "CDS"; locus_tag "CLAFUR5_06022"; orig_transcript_id "CLAFUR5_06022A"; product "Ecp2-2"; protein_id "UJO18017.1";
```

**Comment by alevar** [comment]
Hi,

Thank you for testing our software! Coincidentally we noticed the same issue yesterday and addressed it in the most recent release. The release is currently waiting for approval with bioconda, but static binaries and source code have been updated and included in the latest release on github (https://github.com/alevar/ORFanage/releases/tag/1.1.0). I tested it using your example and it now works as expected (screenshot below). I apologize for the inconvenience and sincerely hope our software is of use to you! Please do not hesistate to reach out to us with any other questions, concerns or suggestions!

![image](https://github.com/alevar/ORFanage/assets/10055267/0ea60e85-b920-4430-ba94-93b969b433ea)

Thank you,

AS

**Comment by alexzaccaron** [comment]
Hi Ales,

Oh, I didn't see there is a fresh new release.
Yep, using the binaries of release 1.1.0 fixed the issue I mentioned.

Thank you,

Alex
