### ISSUE TITLE
issues annotating CDS regions using gencode as reference

### ISSUE THREAD

**Issue by apsteinberg** [alevar/ORFanage#7]
Hi there,

Thanks for the awesome tool! I have some naive questions about using ORFanage that I'm wondering if you could help me with. I have some alternative isoforms assembled with Stringtie2 from short-read sequencing data, for which the reads were mapped on to hg37. I wanted to use gencode as a reference, but I am finding that the output gtf and stats file from ORFanage are completely blank. I'm wondering if there are some extra processing steps I need to take here or I'm making some naive errors with my input commands? These are the commands I am running, as well as the gencode versions. The query here are the assembled isoforms from stringtie2:

`
orfanage  --threads 8 --reference GRCh37.primary_assembly.genome.fa --output ORFanage_out/APS006_normal_ORFanage.gtf --query APS006_merged_normal.gtf --stats ORFanage_out/stats.tsv gencode.v44lift37.annotation.gtf
`
On my terminal I get the following message, which I have truncated to make it a little less complicated because the warnings are redundant:

```
.......
........
Warning: unrecognized parented feature without ID found before its parent:
chr22	HAVANA	Selenocysteine	50655787	50655789	.	+	.	gene_id "ENSG00000073169.15_12"; transcript_id "ENST00000380903.7_7"; gene_type "protein_coding"; gene_name "SELENOO"; transcript_type "protein_coding"; transcript_name "SELENOO-201"; level 2; protein_id "ENSP00000370288.2"; transcript_support_level 1; hgnc_id "HGNC:30395"; tag "basic"; tag "Ensembl_canonical"; tag "MANE_Select"; tag "appris_principal_1"; tag "CCDS"; tag "seleno"; ccdsid "CCDS43034.1"; havana_gene "OTTHUMG00000044645.4_12"; havana_transcript "OTTHUMT00000075003.3_7"; remap_original_location "chr22:+:50217358-50217360"; remap_status "full_contig"; exon_number 9;
sorting reference transcriptome
start removing duplicates
loading query transcriptome
bundling transcriptome
Warning: couldn't find fasta record for '6'!
```
Thanks in advance for your time and help!

Cheers,
Asher

PS Also, I'm wondering if there's a tool you'd recommend I use to extract protein sequences from the output gtf once I get this working?

**Comment by alevar** [comment]
Hi Asher,

Thank you for giving our method a try! I surely hope we can resolve any issues you might have observed so you can resume your analysis.

Our method utilizes a gff_utils library for parsing and extracting data from GTF/GFF files. Both warning in the output you provided are produced by that gff_utils. The first warning regarding the selenocysteine simply notifies that that record can not be properly parsed and added to any existing transcripts. This line in the GTF/GFF will thus be skipped and the warning should not affect the rest of the run.

The second warning, however, indicates that there are issues processing the reference FASTA file itself. I was able to replicate this error, by creating an inconsistency in the fasta index file, resulting in a termination of the process (and an uncaught segfault).

Do you have a fasta index for the reference genome you are using? If so, can you try either deleting it, or renaming it and then re-running the analysis. Our method should construct a new index if one does not already exist, and the new index should alleviate the error you encountered.

I hope this fixes your issues, but if not or you encounter any other difficulties, I will gladly assist in identifying the culprits!

Thank you,

Ales

P.S.: From the author of the gff_utils library I referenced earlied, there is a wonderful package called gffread (available on github: https://github.com/gpertea/gffread, conda, brew, apt, etc). The package is what I normally use for dealing with GTF/GFF files and conversions/extraction of various kinds. For extracting protein sequences specifically, you can use the "-y" option for the aminoacid output or "-x" option for the nucleotide sequence of the protein. There are many other useful feature the software has - hope this helps!

**Comment by apsteinberg** [comment]
Hi Ales,

Thank you for the quick response! Got it, this makes sense. I gave what you suggested a try -- I deleted the fasta index for the reference genome, then allowed ORFanage to construct a new index. This went fine, but I still end up getting the same error message as above, and the resultant gtf and stats files from ORFanage are empty. Please let me know what you would suggest trying next -- I am happy to share these data files with you if it would be helpful in troubleshooting. Also, thank you for suggesting gffread for the protein sequence extraction! That looks like it should work very well.

Happy holidays and talk soon!

Thanks again,
Asher

**Comment by alevar** [comment]
Hi Asher,

Thank you for trying out my original idea, although I am saddened that wasn't the culprit. To clarify, you are still seeing the "Warning: couldn't find fasta record for '6'!" warning? Or is this one now gone and remaining is the unrecognized selenocysteine line only?

I think it would be easiest for me to debug if I had access to a slice of data which would reproduce the described behavior. Let's discuss sharing some simple data over email (ales[dot]varabyou[at]jhu[dot]edu) . I will keep this thread updated according to our findings so that the resolution is visible to others.

Thank you again,

Ales

**Comment by apsteinberg** [comment]
Hi Ales,

Absolutely, thank you! I am unfortuanately still seeing the "Warning: couldn't find fasta record for '6'!" warning.

This all sounds good to me. I'll shoot you an email now (mine is asherps[at]gmail[dot]com).

Thanks,
Asher

**Comment by alevar** [comment]
Hi Asher,

Thank you for providing me some test data and helping me navigate the issue! We found that the transcript assembly protocol followed a reference genome with a additional sequence identifiers which were not part of the data provided to ORFanage. The method was unable to load genome information for those assembled transcripts and exited with an error. I will update the software to handle this error case more gracefully.

Some possible resolutions may include:
1. There exist different nomenclatures for sequence identifiers. If the GTF and FASTA files use different nomenclatures, the GTF file can be converted via `gffread -m` provided with a tab delimited two-column file containing a map between two naming schemes.
2. If the GTF file contains transcripts annotated on sequences not present in the FASTA file, it is best to either update the fasta file or remove any such sequences from the inputs.

I hope our method works well for your purposes and am excited to see the results you obtain using our method!

Thank you,

Ales
